apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-api
          image: academind/kub-dep-tasks:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'MODOB_CONNECTION_URI_PLACEHOLDER'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
